learning_curves:
    domains:
        - subst-eval
        - comb-like
        - one-step-add-eq
    iterations: 12
    agents:
        - name: "Bare"
          root: "/mnt/fs5/poesia/peano/learning/outputs/2022-09-24/21-44-41"
        - name: "Tactic Induction"
          root: "/mnt/fs5/poesia/peano/learning/outputs/2022-09-27/10-21-22"
#        - name: "Tactic Induction + Curriculum"
#          root: "/mnt/fs5/poesia/peano/learning/outputs/2022-09-26/19-45-55"
    output: "learning-curves-2.png"

hydra:
    job:
        chdir: false
