agent:
    eval_every: 1000
    eval_problems: 100
    episodes: 100000
    depth: 5
    search_budget: 100
    rollout_type: BestFirstSearch
    beam_size: 10
    epsilon: 0.1
    max_examples: 10000
    gradient_steps: 2
    only_optimize_when_solved: false
    batch_size: 1000
    train_rollouts_temperature: 0.5
    mask_non_decision_tokens: false

policy:
    type: ContrastivePolicy
    max_negatives_per_episode: 1000
    batch_size: 512
    gru:
        embedding_size: 128
        hidden_size: 512
        layers: 2

job:
    wandb_project: peano
    description: "Test run"
