task: pretrain
utility:
    gru:
        embedding_size: 64
        hidden_size: 256
        layers: 2
    n_epochs: 20
    batch_size: 128
    lr: 0.00005
    interaction: dot-product
    normalize: true

job:
    wandb_project: peano
hydra:
    job:
        chdir: true
